//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("UserId")]
        public string userid { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
