//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int id { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual CartTransaction CartTransaction { get; set; }
    }
}
