//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbluser
    {
        [DisplayName("User Id")]
        [Required(ErrorMessage ="This Field is Required")]
        public string userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public string Email { get; set; }
        public string city { get; set; }
        public string country { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
